### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by RogueMaster** [jimilinuxguy/flipperzero-universal-rf-remote#1]
Assets file would be better with something like:

Filetype: Flipper SubGhz RAW File
Version: 1
UP: /any/subghz/Vehicles/Tesla/Tesla_charge_door_AM270.sub
DOWN: /any/subghz/touchtunes/brute/OK.sub
LEFT: /any/subghz/Vehicles/Tesla/Tesla_charge_door_AM650.sub
RIGHT: /any/subghz/touchtunes/brute/P2.sub
OK: /any/subghz/touchtunes/brute/Pause.sub

Also, applications file needs main function named right for compile as jukebox not universalrf

**Comment by jimilinuxguy** [comment]
The application is universalrf, not jukebox.

The jukebox code was accidentally committed because its being re-worked in another repository to have the bitstring encoder built into the application and not to have to rely on the sub files.

**Comment by RogueMaster** [comment]
Ah ok, so once code is re-worked, the main function will need to be renamed from jukebox to have what you're trying to include in the applications file. :) Thank you for this app!
